# -*- coding: utf-8 -*-

lista = {"afganistan":"kabul",
"albania":"tirana",
"alemania":"berlín",
"andorra":"andorra la vieja",
"angola":"luanda",
"antigua y barbuda":"saint john’s",
"arabia saudita":"riad",
"argelia":"argel",
"argentina":"buenos aires",
"armenia":"ereván",
"australia":"camberra",
"austria":"viena",
"azerbaiyan":"bakú",
"bahamas":"nasáu",
"banglades":"daca",
"barbados":"bridgetown",
"barein":"manama",
"belgica":"bruselas",
"belice":"belmopán",
"benin":"porto novo y cotonú",
"bielorrusia":"minsk",
"birmania":"naipyidó",
"bolivia":"sucre",
"bosnia y herzegovina":"sarajevo",
"botsuana":"gaborone",
"brasil":"brasilia",
"brunei":"bandar seri begawan",
"bulgaria":"sofía",
"burkina faso":"uagadugú",
"burundi":"buyumbura",
"butan":"timbu",
"cabo verde":"praia",
"camboya":"nom pen",
"camerun":"yaundé",
"canada":"ottawa",
"catar":"doha",
"chad":"yamena",
"chile":"santiago de chile",
"china":"pekín",
"chipre":"nicosia",
"ciudad del vaticano":"ciudad del vaticano",
"colombia":"bogotá",
"comoras":"moroni",
"corea del norte":"pionyang",
"corea del sur":"seúl",
"costa de marfil":"yamusukro",
"costa rica":"san josé",
"croacia":"zagreb",
"cuba":"la habana",
"dinamarca":"copenhague",
"dominica":"roseau",
"ecuador":"quito",
"egipto":"el cairo",
"el salvador":"san salvador",
"emiratos arabes unidos":"abu dabi",
"eritrea":"asmara",
"eslovaquia":"bratislava",
"eslovenia":"liubliana",
"espana":"madrid",
"estados unidos":"washington d c",
"estonia":"tallin",
"etiopia":"adís abeba",
"filipinas":"manila",
"finlandia":"helsinki",
"fiyi":"suva",
"francia":"parís",
"gabon":"libreville",
"gambia":"banjul",
"georgia":"tiflis",
"ghana":"acra",
"granada":"saint george",
"grecia":"atenas",
"guatemala":"ciudad de guatemala",
"guyana":"georgetown",
"guinea":"conakri",
"guinea-bisau":"bisáu",
"guinea ecuatorial":"malabo",
"haiti":"puerto príncipe",
"honduras":"tegucigalpa",
"hungria":"budapest",
"india":"nueva delhi",
"indonesia":"yakarta",
"irak":"bagdad",
"iran":"teherán",
"irlanda":"dublín",
"islandia":"reikiavik",
"islas marshall":"majuro",
"islas salomon":"honiara",
"israel":"jerusalén",
"italia":"roma",
"jamaica":"kingston",
"japon":"tokio",
"jordania":"amán",
"kazajistan":"astaná",
"kenia":"nairobi",
"kirguistan":"biskek",
"kiribati":"tarawa",
"kuwait":"kuwait",
"laos":"vientián",
"lesoto":"maseru",
"letonia":"riga",
"libano":"beirut",
"liberia":"monrovia",
"libia":"trípoli",
"liechtenstein":"vaduz",
"lituania":"vilna",
"luxemburgo":"luxemburgo",
"madagascar":"antananarivo",
"malasia":"kuala lumpur",
"malaui":"lilongüe",
"maldivas":"malé",
"mali":"bamako",
"malta":"la valeta",
"marruecos":"rabat",
"mauricio":"port-louis",
"mauritania":"nuakchot",
"mexico":"ciudad de méxico",
"micronesia":"palikir",
"moldavia":"chisináu",
"monaco":"mónaco",
"mongolia":"ulán bator",
"montenegro":"podgorica",
"mozambique":"maputo",
"namibia":"windhoek",
"nauru":"yaren",
"nepal":"katmandú",
"nicaragua":"managua",
"niger":"niamey",
"nigeria":"abuya",
"noruega":"oslo",
"nueva zelanda":"wellington",
"oman":"mascate",
"paises bajos":"ámsterdam",
"pakistan":"islamabad",
"palaos":"melekeok",
"panama":"panamá",
"papua nueva guinea":"port moresby",
"paraguay":"asunción",
"peru":"lima",
"polonia":"varsovia",
"portugal":"lisboa",
"reino unido de gran bretana e irlanda del norte":"londres",
"reino unido":"londres",
"republica centroafricana":"bangui",
"republica checa":"praga",
"republica de macedonia":"skopie",
"macedonia":"skopie",
"republica del congo":"brazzaville",
"republica democrática del congo":"kinsasa",
"republica dominicana":"santo domingo",
"republica sudafricana":"bloemfontein, ciudad del cabo y pretoria",
"sudafrica":"bloemfontein, ciudad del cabo y pretoria",
"ruanda":"kigali",
"rumania":"bucarest",
"rusia":"moscú",
"samoa":"apia",
"san cristobal y nieves":"basseterre",
"san marino":"san marino",
"san vicente y las granadinas":"kingstown",
"santa lucia":"castries",
"santo tome y principe":"santo tomé",
"senegal":"dakar",
"serbia":"belgrado",
"seychelles":"victoria",
"sierra leona":"freetown",
"singapur":"singapur",
"siria":"damasco",
"somalia":"mogadiscio",
"sri lanka":"sri jayewardenepura y colombo",
"suazilandia":"babane y lobamba",
"sudan":"jartum",
"sudan del sur":"yuba",
"suecia":"estocolmo",
"suiza":"berna",
"surinam":"paramaribo",
"tailandia":"bangkok",
"tanzania":"dodoma",
"tayikistan":"dusambé",
"timor oriental":"dili",
"togo":"lomé",
"tonga":"nukualofa",
"trinidad y tobago":"puerto españa",
"tunez":"túnez",
"turkmenistan":"asjabad",
"turquia":"ankara",
"tuvalu":"fongafale",
"ucrania":"kiev",
"uganda":"kampala",
"uruguay":"montevideo",
"uzbekistan":"taskent",
"vanuatu":"port vila",
"venezuela":"caracas",
"vietnam":"hanói",
"yemen":"saná",
"yibuti":"yibuti",
"zambia":"lusaka",
"zimbabue":"harare"}
